# Generated by Django 5.1.4 on 2025-01-14 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

def set_default_event_list(apps, schema_editor):
    EventList = apps.get_model('blog', 'EventList')  # Get the EventList model
    Post = apps.get_model('blog', 'Post')  # Get the Post model

    # Create a default EventList object
    default_event_list = EventList.objects.create(name='Default Event List', slug='default-event-list')

    # Assign this EventList to all existing Post objects
    for post in Post.objects.all():
        post.event_list = default_event_list
        post.save()
class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='event_list',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to='blog.eventlist',
                null=True,  # Allow null temporarily
            ),
        ),
        migrations.RunPython(set_default_event_list),  # Run the data migration
        migrations.AlterField(
            model_name='post',
            name='event_list',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to='blog.eventlist',
                null=False,  # Remove nullability after data migration
            ),
        ),
    ]
